### ISSUE TITLE
The details of parameter setting

### ISSUE THREAD

**Issue by Yu-0025** [Han8931/rsmi_nlp#1]
Hello,
I've been working with the RoBERTa model on the AG News dataset and have configured the parameters as per my understanding. However, the performance of the RSMI model hasn't met the superior results mentioned in your paper. I'm concerned that my parameter settings might be wrong. Could you please review them for me? Your assistance would be greatly appreciated. Thank you!

- exp_dir: ./experiments/cls/2023_12_12/
- exp_msg: CLS Transformer
- gpu_idx: 10
- eval: False
- model_dir_path: ../../models/roberta/
- save_model: rsmi_roberta_ag
- load_model: cls_trans
- save: True
- seed: 1
- device: cuda
- w_gn: 1.0
- noise_eps: 0.4
- single_layer: False
- nth_layers: 3
- num_ensemble: 5
- binom_ensemble: 50
- pooler_output: False
- custom_forward: True
- binom_n_eval: 5
- sample_mask: True
- mask_batch_ratio: 1.0
- rand_mask: True
- grad_mask_sample: True
- ens_grad_mask: rand
- two_step: False
- multi_mask: 4
- mask_idx: 50264
- vote_type: max
- epochs: 10
- batch_size: 24
- model: roberta
- optim: adamw
- scheduler: linear
- lr: 1e-05
- dropout: 0.1
- clip: 1.0
- margin: 0.5
- embed_dim: 768
- dataset: ag
- num_classes: 4
- pad_idx: 1
- max_seq_length: 256
- binom_p: False
- alpha_p: 0.7

Model: rsmi_roberta_ag_9 || FileName: _rsmi_roberta_ag_9_test.csv || Attack: textfooler          
Multi_Mask: 4                                                                                    
Trials: 1000 || # Success: 325 || # Failed: 614 || # Skipped: 61                                 
ASR: 0.3461 || AAcc: 0.6140
====================================================================================================
C-Acc: 93.90 || R-Acc: 61.40 || ASR: 34.61 || Pert: 15.84 || Avg-Q: 369.42 || AvgS-Q: 186.90 || AvgF-Q: 466.03
Total Elapsed Time: 3:08:47.143659
Save data...: ./data/ag_textfooler_rsmi_roberta_ag_9_test.csv

**Comment by Han8931** [comment]
Hi, 

Can you try to set two_step to True?
You can also lower the nth_layers.  

Alternatively, try to vary random seed too. 

I will try to clean my code. 

Thanks for trying to use RSMI.

**Comment by penguinwang96825** [comment]
What does `nth_layers` do?

**Comment by Han8931** [comment]
It controls the number of random noise layers.
